name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Python Installation
        run: |
          python3 --version

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip --break-system-packages
          python3 -m pip install pytest --break-system-packages

      - name: Run Tests
        run: |
          python3 -m pytest src/test_addition.py -v
